示例文件，代码逻辑与 `transformer/main.py` 基本相同，只是以 Jupyter Notebook 形式编写。

In [1]:
from ml_fall_2024_final.dataset import BikeDataset, read_test_data, read_train_data
from ml_fall_2024_final.transformer.model import TransformerTimeSeries
from ml_fall_2024_final.transformer.plotting import plot_window_prediction, print_window_mse_mae
from ml_fall_2024_final.transformer.trainer import run_experiment
from ml_fall_2024_final.utils import save_model

In [ ]:
train_data = read_train_data()
test_data = read_test_data()

train_data

,dteday,season,yr,mnth,hr,holiday,weekday,workingday,weathersit,temp,atemp,hum,windspeed,cnt
0,2011-01-01,1,0,1,0,0,6,0,1,0.24,0.2879,0.81,0.0000,16
1,2011-01-01,1,0,1,1,0,6,0,1,0.22,0.2727,0.80,0.0000,40
2,2011-01-01,1,0,1,2,0,6,0,1,0.22,0.2727,0.80,0.0000,32
3,2011-01-01,1,0,1,3,0,6,0,1,0.24,0.2879,0.75,0.0000,13
4,2011-01-01,1,0,1,4,0,6,0,1,0.24,0.2879,0.75,0.0000,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15211,2012-10-01,4,1,10,0,0,1,1,1,0.46,0.4545,0.72,0.1045,45
15212,2012-10-01,4,1,10,1,0,1,1,1,0.44,0.4394,0.77,0.0896,18
15213,2012-10-01,4,1,10,2,0,1,1,1,0.46,0.4545,0.72,0.0000,12
15214,2012-10-01,4,1,10,3,0,1,1,1,0.44,0.4394,0.77,0.0000,7
15215,2012-10-01,4,1,10,4,0,1,1,1,0.42,0.4242,0.82,0.1045,10

In [3]:
train_dataset_short = BikeDataset(train_data, output_window="short")
test_dataset_short = BikeDataset(test_data, output_window="short")

train_dataset_long = BikeDataset(train_data, output_window="long")
test_dataset_long = BikeDataset(test_data, output_window="long")

In [4]:
RUN_TIMES = 5

In [ ]:
print("短期预测 (96 小时)")

model_short = TransformerTimeSeries(output_window="short")
preds_short, truth_short, _mse_short, _mae_short = run_experiment(
    model=model_short,
    train_dataset=train_dataset_short,
    test_dataset=test_dataset_short,
    run_times=RUN_TIMES,
)
save_model(model_short, "transformer_short")

In [ ]:
# 绘制短期预测结果
last_window_preds_short = tuple(pred[-1] for pred in preds_short)
last_window_truth_short = truth_short[-1]

print_window_mse_mae(last_window_preds_short, last_window_truth_short)
fig = plot_window_prediction(
    last_window_preds_short,
    last_window_truth_short,
    title="Short-term Prediction (96 Hours)",
)
fig.show()

In [ ]:
print("长期预测 (240 小时)")

model_long = TransformerTimeSeries(output_window="long")
preds_long, truth_long, _mse_long, _mae_long = run_experiment(
    model=model_long,
    train_dataset=train_dataset_long,
    test_dataset=test_dataset_long,
    run_times=RUN_TIMES,
)
save_model(model_long, "transformer_long")

In [ ]:
# 绘制长期预测结果
last_window_preds_long = tuple(pred[-1] for pred in preds_long)
last_window_truth_long = truth_long[-1]

print_window_mse_mae(last_window_preds_long, last_window_truth_long)
fig = plot_window_prediction(
    last_window_preds_long,
    last_window_truth_long,
    title="Long-term Prediction (240 Hours)",
)
fig.show()